---
- name: "Install Packages"
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ packages.to_install }}"

- name: "Configure New APP in HAProxy"
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644
  with_dict: "{{ new_app }}"
  notify: "Apply new configuration for HAProxy"

- name: "Set up high availability with Keepalived"
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: 0644
  notify: "Apply new configuration for Keepalived"

- name: "Inicialize systemd services"
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ services.to_enable }}"
